### ISSUE TITLE
Graphs not being generated

### ISSUE THREAD

**Issue by tacerus** [torproject/nyx#39]
Hi,

Upon attempting to use nyx on a Slackware system the graphs remain empty. I assume it is an dependency issue that was not caught at install time. I resolved all the dependency issues it showed during the installation by compiling Python with SQLITE support and it seems that the program is fully working, with the only exception being the graphs.

Traffic does seem to be captured as I am able to see connections.

Any idea what else I might need to install?

I also installed nyx on an openSUSE system, where immediately upon launching pretty graphs were generated.

Thanks!
Georg

Picture of expected output (also moving): https://hugz.io/6w739c/Screenshot_20210610_103207.png
Picture of observed output (no reaction): https://hugz.io/4yy54p/Screenshot_20210610_103300.png

**Comment by atagar** [comment]
Hi tacerus. Have you tried the following?

https://nyx.torproject.org/#missing_bandwidth_graph

**Comment by Minoru** [comment]
I ran into the same problem on Debian stable with Nyx 2.1.0 and Tor 0.4.5.10. The culprit was this line in ~/.nyx/config:

```
color_override none
```

As documentation explains, this simply replaces all colours with "no color", which obviously makes the graph invisible.

The reason I had this line in my config at all is that I copied the entire thing from /usr/share/doc/nyx/nyxrc.sample.gz which is shipped with the Debian package. Here's a copy: [nyxrc.sample.gz](https://github.com/torproject/nyx/files/7499661/nyxrc.sample.gz) This sample claims it contains defaults except otherwise noted, but I actually had to comment out `tor_chroot`, `logging_filter`, `write_logs_to`, `config_order`, and `connection_order` to even get Nyx to start; the defaults in the sample config are just not accepted by Nyx.

I'll go report that to Debian now; just wanted to share here in case someone else bumps into the same problem.

**Comment by atagar** [comment]
> As documentation explains, this simply replaces all colours with "no color"

That is incorrect. Rather, it means "use the default colors", hence why it's the default. Link welcome if you see any documentation that contradicts that. The [nyxrc config docs](https://nyx.torproject.org/#configuration) don't discuss the 'none' option.

**Comment by Minoru** [comment]
> it means "use the default colors", hence why it's the default. Link welcome if you see any documentation that contradicts that.

Well, https://github.com/torproject/nyx/blob/319f1348f28a226f287b96ea3f1f2e698612b8b3/web/nyxrc.sample#L15

If "this hue" is "none", then one could think it means "no hue", not "a default hue". This is mostly on me, I should have read *all* the docs, but still, this comment could be better. I'll submit a pull request to improve it.

> The nyxrc config docs don't discuss the 'none' option.

Which is also a problem. Why doesn't documentation discuss the default value of a setting? That'll be a part of my PR too.

The original issue — i.e. `color_override none` hiding the graph— was already fixed by ed031ca750be06e4134d58b81448e60020c0cfd8.

**Comment by atagar** [comment]
> If "this hue" is "none", then one could think it means "no hue", not "a default hue".

That's fair. In the [usual location](https://nyx.torproject.org/#configuration) folks look to for configuration options it's described as "Replaces most color with this hue."

I don't mind keeping this open in case someone would care to tweak its wording.
