### ISSUE TITLE
Nyx shows 2500 inbound connections and 1500 outbound, but there's almost zero traffic.

### ISSUE THREAD

**Issue by debian-user-france1** [torproject/nyx#51]
Is it possible, that nyx shows me A LOT of connections that are + 2.1d old? All 2.1d. Why do I have so many inbound connections? 
Tor uses ~8% cpu and ~500MB RAM. 

I only have an average of 190KB/s! My relay has the Fast flag.

**Comment by atagar** [comment]
Hi france1. Nyx uses system tools (like netstat, lsof, etc) to receive a list of your connections then correlates the ports to with tor's configuration to make sense of what's inbound, outbound, controllers, etc.

Connection uptime is not available from the system so the maximum duration Nyx will present is the duration that you've been running Nyx. In other words if you've been running Nyx for two days and have a bunch of connections that are '2d' old that means those connections have been around since you started Nyx.

Unfortunately I can't tell remotely tell you why you have so many connections but it's not necessarily a cause for concern. Busy relays tend to have a ton. To get further information you'll need to use system tools like netstat to investigate.

If you'd care to remove Nyx from the picture here's a Stem script to get similar connection information...

https://stem.torproject.org/tutorials/examples/relay_connections.html

Feel free to reopen if you have any further questions.

**Comment by debian-user-france1** [comment]
I actually can't reopen it... I'm just confused why I have so many connections but there is now an average of 2500KB/s only. My internet provider is shitty - if I have too many connections open they I'll have to wait a long time until sited load since they seem to slow down us (not the internet speed but the connections that we make).
I just wondered if that value could be wrong that nyx shows. I don't want to reopen it.
